# Generated by Django 4.2 on 2023-05-24 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='borrowedbook',
            options={'verbose_name': 'Забронированная книга', 'verbose_name_plural': 'Забронированные книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В доступе'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Забронирована'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_borrowed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата брони'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
